name: 03 - Checkout Demo

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  explore:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List repository
        run: |
          echo "Repository contents:"
          ls -la
          echo ""
          echo "Current directory"
          pwd
      
      - name: Git information
        run: |
        echo "Branch: ${{ github.ref}}"
        echo "Commit: ${{ github.sha}}"
        echo "Actor: ${{ github.actor}}"